apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skiff
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: hello-world-tls
      hosts:
        - hello-world.duyker.nl
