apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skiff
spec:
  rules:
    - http:
        host: www.example.com
        paths:
          - backend:
              service:
                name: skiff
                port:
                  number: 80
            path: /
            pathType: Prefix
