apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: k8s-skiff

resources:
  - service.yaml
  - secret.yaml
  - ingress.yaml
  - configmap.yaml
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: k8s-skiff
